In [6]:
import csv
import pandas as pd

df = pd.read_csv("C:/Users/Ryan Goh/Desktop/AAER/aaer_no_nan3.csv")
df

,aaer_release_to_party_fkey,aaer_release_fkey,raw_name,party_type_fkey,type,auditor_fkey,auditor_name,auditor_affiliate_fkey,aud_aff_name,cik,company_name,law_firm_fkey,law_firm_name
0,245,2720,"Neurotrope, Inc.",3,Entity,NaN,NaN,NaN,NaN,1513856,"Neurotrope, Inc.",NaN,NaN
1,4,24,Maxim Integrated Products Inc,3,Entity,NaN,NaN,NaN,NaN,743316,MAXIM INTEGRATED PRODUCTS INC,NaN,NaN
2,6,18,Precipio Inc,3,Entity,NaN,NaN,NaN,NaN,1043961,"Precipio, Inc.",NaN,NaN
3,12,3,Finisar Corp,3,Entity,NaN,NaN,NaN,NaN,1094739,FINISAR CORP,NaN,NaN
4,13,3,Oclaro Inc,3,Entity,NaN,NaN,NaN,NaN,1110647,"OCLARO, INC.",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2440,10413,3181,Avalanche International Corp.,3,Entity,NaN,NaN,NaN,NaN,1537169,"AVALANCHE INTERNATIONAL, CORP.",NaN,NaN
2441,10416,3182,Longfin Corp,3,Entity,NaN,NaN,NaN,NaN,1699683,Longfin Corp,NaN,NaN
2442,10425,3186,Akazoo S.A.,3,Entity,NaN,NaN,NaN,NaN,1767043,Akazoo S.A.,NaN,NaN
2443,10454,3195,"Adaptive Medias, Inc.",3,Entity,NaN,NaN,NaN,NaN,1428397,"Adaptive Medias, Inc.",NaN,NaN
2444,10466,3190,"Palmyra Energy Ventures Fund I, LP",3,Entity,NaN,NaN,NaN,NaN,1667590,"Palmyra Energy Ventures Fund I, L.P.",NaN,NaN

In [11]:
#i want to get the cik as a list
cik = df['cik']
cik_list = list(cik)

final = []
for c in cik_list:
  if len(str(c)) < 10:
    #count the diff in length
    n = 10 - len(str(c))
    zero_string = n * '0'
    final_c = zero_string + str(c)
    final.append(final_c)

final

#save this into a csv
#save the file to path
outdir = 'C:/Users/Ryan Goh/Desktop/AAER'

pd.DataFrame(final).to_csv(f"{outdir}/cik.csv")